sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_1ee86b879c1f_key -iv $encrypted_1ee86b879c1f_iv
  -in travis/secrets.tar.enc -out travis/secrets.tar -d
- tar xvf travis/secrets.tar -C ./travis
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- rm "${JAVA_HOME}/lib/security/cacerts"
- ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
- mvn clean install
- |
  set -e
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
     echo "Importing GPG key into keyring"
     gpg --fast-import travis/codesigning.asc
     mvn versions:set -DnewVersion="$COMMIT_SHORT"

     echo "Running release"
     mvn --settings travis/settings.xml deploy -Prelease -DskipTests=true
  fi
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - secure: bfTXTXWpHR3oEaK27EtoZm+7kNzyeG1X+TYb/cc7y0YwWVAq909p1TA67Zm0H8+8B3onvdjRKT/vmPtrjndZ1JGdErzdWB0aQS6POrakksJ1dSTlniR2jUWwU2T6uSGTg81mGd2SBOGhHxTim1dJbEDLA9NcFZMQroK3tfKgtlKTW7mxQDElVJ8IDj9+Nr/gpYJdIl8ne6c3ghYBR89xXzADm4IyIAVloz5FFwldtgkcz2Y6dquTQWA/KR6yV4SgEeSzrvtf9/btxQvfxAog0taKuzezPub4aCAfQt+AbujvVoTYPa+V6RfzDmPpi9X/e+pX9y6nFiC+tLsZgbxd0Ou+abqaiY3PYNw6phcMr/TWmdWmbjlHLbtnjUzVhYGwsIxGhjgdnVTrKEUZrrEIBV/oKpB3BP+XkjtoYRSc3ducQsnhgPunDCOxZKZo2xJI0HLYUwsKNsLVmAXL0DG6OPuSs41YEkExHPLp4fQbUCNnMAfASgq3nKi1oWv/4F/558HdkRYBli/Z4MT3zQ0SA8arjbHDncJmHDAyk2q/yiSdRYNsld9JYCmeaCXcGwL8MePJTNQYALCMj2VS3uHWpkYb7MlsSTJnEF6gC+FDU6ltBVAk66Rn+N8E+N4kJJO7rm6oxVrK1qTZvG8TmT/f1mM9n0Yg7yVfAhgfNDZulGI=
  - GPG_KEY_NAME=navikt
  - secure: enlLQvkhmJR6U0NxZLfPmEzkAsvoJqRCZw3QL6LfYEWEqnB4toN5eZO9MdYkDcBP8O4FaRXHlFDiAkKIBW/Hg4gX913BxQyOVIHm9gXQdB8k5eRpplYBZGktPUAArGGfBe1JmH+srJEEG1zIO7bS091eWOPEcT7gkfcj21+rUtvnZ0zcxGz53oVS4nxmcCL7wtOydM2kT8FkfOHdN+vudITymsKNa3bJ1WwYyGFCRyWzv2VZRnAwgOuJ2VlIFWLB+GwvAwoti+HTgTUFVSJBtZKGC1QgjbnT4AZNGRkV9NpbdH+XEOl/5lpPz6WEh30Rh1B7rXBRttwyvLIi4MWduiFImhR66GT2A1JZzg6wsStBlwrodTc/z4qY4uSRZepuSYUk3qZmNVjDgfV9m7Zvp2j3U6cpEbikInIfqt4R47Io1USHY5CVwuL0AFbbAUp0gi/wLDPjTphiwqw4CWEcM/SZIPRaS/E1Z6UK+sPvT/g/L6K1CK8vccgk6Bctl8WRF0ep7B74UMi+OEjefM/cifSKkZ9mqfpOdDCttvnGAWSfa4+Ai4wkVvYurcgdvYwyHS5f1CFjPAE/8ilO8+JhEmZTeJFM2ilLmoV/WRb9AOnDwah39rAWE4Z49QB6R/Z09xM9zIUofuaCesBbu5c7jBJP2P97TAJn+r32uQqzcOc=

