sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_1ee86b879c1f_key -iv $encrypted_1ee86b879c1f_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
script:
- mvn clean install
- |
  set -e
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
     echo "Importing GPG key into keyring"
     gpg --fast-import travis/codesigning.asc
     mvn versions:set -DnewVersion="$COMMIT_SHORT"

     echo "Running release"
     mvn --settings travis/settings.xml deploy -Prelease -DskipTests=true
  fi
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - GPG_KEY_NAME=navikt
  - secure: YCxC9IgvG1XrVch0L6oPfNddbf//4cku4gIoMu7XM2dKnay39O1xCPxyMoWZs9JUHRCxcrR8+lYcXiyJ8sqDW8//8NyA3D0goG1rqHP6LlAp0B7A+CYPxUTPdUodihRkAzuTqT0ppLf3A2xdQ7yBiPs2RNjIBc/tLXZ8t4rrQWkPJ4/TadnyAi9h6hPmBwE4LLzW5x8cqFylR6aU98Km1m1TZyCOgsiKxqtYfHm6/UsqgwLel/GBrnIof1CcEYeqGGu0kD4UME5S56GUIAzebckDsivx+/acn3ZDBwYs3LMEsdiGS5i5qJr//wO4rGebAr1I2mUT5NUunWP826CkEJnkGnVMFd8zDncbpKdG8AJplA1gZuV+m28bNmJlf1bIp8s+m9vdfgVDGJoFndmCVbwYHGtx+K7QJsuui7YoOgt9gPtLcHP73pAuYP5H9isQFKYiANGyYXUlnj61roHRUNfzXcwFl9niJN5hjnwUMlLmKqIGXxcWANMiqwQ5PSmoigPby7v8MRwGiNdE9DLiUAYgaeEIeqvAF4JtpXvxJ/Rh7D1RYPNHiDHvGAzOGK2QvtGA7nr4TA8Xe3Vu1oKIghTqVSOask/psErPjftC31LdmrlUneJ7jIuaEZ4E1tJBlXCqq9oOY5bqQluETNWrjZThoKdre86lwcMwab4ue7I=
  - secure: F/bZSNv0W6dRr8J3DBM54/hFk0y1FNYGr7KTuWoOIAn5W+p3Z3/h8j+4Q+3pudcutbXN9+pw5oY1e2xdZMowG1t94XXlBneVRl1l8SxldjjTD7zppKlZpEuxWqIX1du09SfzIWLt6NbqhJc7trili+6Z6UhVrk3lDnP51UWoXg9CdkkGc8ko8nIFQPehFuZc4Y/GpqYcgE1IKoIwh24QceY98NpO/R96ZMUkcbMxFHxgsc8RmMUk409sXBo8CSXYcSHUaSfqpr0OR4w056undh7BL9qqJqihHrQcZZ/1Tkm3A7TJW/qPZT2l0QZqHuh1K4EKRJz7YYBruIMU8EsTOz4t3nTDISkKWGO0cFxGM4EQCAOv958P8mKRvsBf62I5Nl1tIhbjydtrUk3ALgelSOaNdQo+v3AKL8uq7VuV0tEhP7acKxExiei1Qq0avQ9D31/QFYLVvBTzaRxsYoOx6lGVxq+3Mfqrp0LVokvM6mzFyvtCnlgtKEi9Mdm5JTbx6eBJ3KdKcaLMT2izR4WRU66t621yRQ9xEIuhMSZyZAo47yrBKFQT8AVMoMTEYpwLRKHxUjGdy4RC/iceskjtk51Qmy8/3J0/BQKH0OLn5TpXZLEocx5kjs9IrDW/bBx+ykySq6nN3JbSVu2TiWrGcibmrUG0okQfayTC+hH10go=
